In [15]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])
z=x+y
print(z)
print('_'*40)
p=y-x
print(p)
print('_'*40)
#normal multiplication element wise
q=x*y
print(q)
print('_'*40)
#matrix multiplication using @ symbol
r=x@y
print(r)
print('_'*40)
#division
s=y/x
print(s)
print("*"*30)
#floor division
t=y//x
print(t)
print("*"*30)
#exponention
u=y**x
print(u)
print("*"*30)
#remainder
v=y%x
print(v)
print("*"*30)
#transpose : rows columns bannxan, columns rows bannaxan
print(x.transpose())

[[12 14]
 [16 18]]
________________________________________
[[10 10]
 [10 10]]
________________________________________
[[11 24]
 [39 56]]
________________________________________
[[37 40]
 [85 92]]
________________________________________
[[11.          6.        ]
 [ 4.33333333  3.5       ]]
******************************
[[11  6]
 [ 4  3]]
******************************
[[   11   144]
 [ 2197 38416]]
******************************
[[0 0]
 [1 2]]
******************************
[[1 3]
 [2 4]]
