In [2]:
#data distribution is a list of all possible values, how often each value occurs.
#such lists are important when working with statistics and data science
from numpy import random
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0], size=(3,5))
print(x)

[[7 7 7 5 5]
 [7 7 7 7 5]
 [5 5 3 7 3]]


In [3]:
from numpy import random
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))
print(x)

[7 7 3 5 7 7 5 3 5 3 7 7 7 7 7 5 3 7 5 7 5 7 7 7 5 7 5 3 7 7 7 7 7 5 7 7 5
 7 7 7 7 3 7 7 5 7 3 7 5 3 7 7 7 7 7 7 7 7 7 7 7 7 7 5 7 7 7 7 5 7 7 7 3 7
 5 3 7 5 7 5 7 5 3 7 7 5 5 7 5 7 7 7 7 5 5 5 7 7 5 5]
