In [2]:
#data distribution is a list of all possible values, how often each value occurs.
#such lists are important when working with statistics and data science
from numpy import random
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0], size=(3,5))
print(x)

[[7 7 7 5 5]
 [7 7 7 7 5]
 [5 5 3 7 3]]


In [3]:
from numpy import random
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=(100))
print(x)

[7 7 3 5 7 7 5 3 5 3 7 7 7 7 7 5 3 7 5 7 5 7 7 7 5 7 5 3 7 7 7 7 7 5 7 7 5
 7 7 7 7 3 7 7 5 7 3 7 5 3 7 7 7 7 7 7 7 7 7 7 7 7 7 5 7 7 7 7 5 7 7 7 3 7
 5 3 7 5 7 5 7 5 3 7 7 5 5 7 5 7 7 7 7 5 5 5 7 7 5 5]


In [16]:
from numpy import random
x=random.choice([1,2,9,8,7], p=[0.1,0.5,0.2,0.2,0.0],size=[10])
print(x)

[2 2 9 9 9 2 9 2 2 2]


In [26]:
import numpy as np
arr=np.array([1.2,2.0,3.9,4.0,5.1])
print(arr)
print(arr.itemsize)
arr.dtype

[1.2 2.  3.9 4.  5.1]
8


dtype('float64')

In [1]:
from numpy import  random
import numpy as np
arr=np.array([1,2,3,4,5,6])
random.shuffle(arr)
print(arr)


[3 2 4 5 1 6]


In [3]:
arr1= random.permutation(arr)
print(arr)
print(arr1)

[3 2 4 5 1 6]
[3 1 4 2 6 5]
