In [1]:
import numpy as np
arr =np.array([1, 2,3,4,5,6,7,8,])
for x in arr:
    print(x)

1
2
3
4
5
6
7
8


In [3]:
#Iterating 2D array
arr=np.array([[2,4,6,8],[10,12,14,16]])
for x in arr:
    print(x)
for x in arr:
    for y in x:
        print(y)

[2 4 6 8]
[10 12 14 16]
2
4
6
8
10
12
14
16


In [6]:
#Iterating 3D array
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[3,5,7,9,11],[11,13,15,17,21]]])
print(arr)
print(arr.ndim)
for x in arr:
    for y in x:
        for z in y:
            print(z)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 3  5  7  9 11]
  [11 13 15 17 21]]]
3
1
2
3
4
5
6
7
8
9
10
3
5
7
9
11
11
13
15
17
21


In [9]:
#iterating arrays using nditer()
arr=np.array([[[1,2,3,4,],[6,7,8,9,]],[[2,4,6,8],[10,12,14,16]]])
for x in np.nditer(arr):
    print(x)
#enumerated iterationg using ndenumerate()
for y, x in np.ndenumerate(arr):
    print(y,x)


1
2
3
4
6
7
8
9
2
4
6
8
10
12
14
16
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 6
(0, 1, 1) 7
(0, 1, 2) 8
(0, 1, 3) 9
(1, 0, 0) 2
(1, 0, 1) 4
(1, 0, 2) 6
(1, 0, 3) 8
(1, 1, 0) 10
(1, 1, 1) 12
(1, 1, 2) 14
(1, 1, 3) 16
b'1'
b'2'
b'3'
b'4'
b'6'
b'7'
b'8'
b'9'
b'2'
b'4'
b'6'
b'8'
b'10'
b'12'
b'14'
b'16'


In [10]:
#iterating array with different data types
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'6'
b'7'
b'8'
b'9'
b'2'
b'4'
b'6'
b'8'
b'10'
b'12'
b'14'
b'16'


In [11]:
#iterating wiht different step size
for x in np.nditer(arr[:,::2]):
    print(x)

1
2
3
4
2
4
6
8
