In [4]:
import numpy as np
arr1= np.array([[1,2,3], [4,5,6]])
arr2= np.array([[11,13,15],[17,19,21]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 1  2  3 11 13 15]
 [ 4  5  6 17 19 21]]


In [7]:
arr3=np.array([1,2,3])
arr4=np.array([4,5,6])
arr5=np.stack((arr3,arr4),axis=1)
print(arr5)
arr6=np.stack((arr3,arr4),axis=0)
print(arr6)
            

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [19]:
#Numpy Splitting Array
arr7=np.array([1,2,3,4,5,6,7,8,9,10,11])
newarr1=np.array_split(arr7,4)
print(newarr1)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11])]


In [21]:
#Searching Arrays
arr8=np.array([1,2,3,4,5,3,6,2,3,9,8,3])
x=np.where(arr8==3)
print(x)
#find the indexes where the values are even
y=np.where(arr8%2==0)
print(y)
#find the indexes where the values are odd:
z=np.where(arr8%2==1)
print(z)

(array([ 2,  5,  8, 11], dtype=int64),)
(array([ 1,  3,  6,  7, 10], dtype=int64),)
(array([ 0,  2,  4,  5,  8,  9, 11], dtype=int64),)
