# Welcome to Numpy Learning

In [3]:
import numpy as np

In [4]:
myarr = np.array([1,2,3,4,5])

In [5]:
myarr

array([1, 2, 3, 4, 5])

In [6]:
arr = np.array([2,4,6,8,10])

In [7]:
print(arr)

[ 2  4  6  8 10]


In [8]:
type(arr)

numpy.ndarray

In [10]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
arr3=np.zeros((3,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
arr4=np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
arr5=np.identity(2)
arr5

array([[1., 0.],
       [0., 1.]])

In [19]:
arr6=np.arange(5,10)
arr6

array([5, 6, 7, 8, 9])

In [18]:
arr6=np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [20]:
arr7=np.linspace(10,20,7)
arr7

array([10.        , 11.66666667, 13.33333333, 15.        , 16.66666667,
       18.33333333, 20.        ])

In [21]:
arr8=np.linspace(3,30,3)
arr8

array([ 3. , 16.5, 30. ])

In [22]:
arr9=arr8.copy()
arr9

array([ 3. , 16.5, 30. ])