In [2]:
#Generate Random Array
#Integers
from numpy import random
x=random.randint(100,size=(5))
print(x)


[41 28 96 17 94]


In [3]:
#Float
y=random.rand(5)
print(y)

[0.98149384 0.3903126  0.12224981 0.65081155 0.54403279]


In [4]:
#2 dimensional array
x=random.randint(100,size=(3,5))
print(x)
y=random.rand(3,5)
print(y)

[[11 53  0  5 24]
 [40 38 72 65 31]
 [35 39 23 72 55]]
[[0.60728688 0.04213033 0.34622888 0.70319034 0.30544333]
 [0.40557965 0.2880525  0.65933572 0.44628027 0.85395909]
 [0.49288569 0.75413618 0.83154865 0.8587467  0.94345189]]
